kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{},"finalizers":["foregroundDeletion"],"labels":{"app.kubernetes.io/instance":"java-spring-petclinic"},"name":"petclinic-app","namespace":"pipelines"},"spec":{"host":"petclinic-app-pipelines.apps.enentodemocluster.janus.com","port":{"targetPort":8080},"to":{"kind":"Service","name":"petclinic-service","weight":100},"wildcardPolicy":"None"},"status":{"ingress":[{"conditions":[{"lastTransitionTime":"2021-09-28T13:31:37Z","status":"True","type":"Admitted"}],"host":"petclinic-app-pipelines.apps.enentodemocluster.janus.com","routerCanonicalHostname":"router-default.apps.enentodemocluster.janus.com","routerName":"default","wildcardPolicy":"None"}]}}
  resourceVersion: '3632633'
  name: petclinic-app
  uid: cea4b123-8b93-4604-954e-e2ae7d13d128
  creationTimestamp: '2021-09-28T13:32:55Z'
  managedFields:
    - manager: argocd-application-controller
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2021-09-28T13:33:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:finalizers':
            .: {}
            'v:"foregroundDeletion"': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:host': {}
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
        'f:status':
          'f:ingress': {}
  namespace: pipelines
  finalizers:
    - foregroundDeletion
  labels:
    app.kubernetes.io/instance: java-spring-petclinic
spec:
  host: petclinic-app-pipelines.apps.enentodemocluster.janus.com
  to:
    kind: Service
    name: petclinic-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
status:
  ingress:
    - host: petclinic-app-pipelines.apps.enentodemocluster.janus.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2021-09-28T13:32:56Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.enentodemocluster.janus.com
