kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: petclinic-app
  namespace: pipelines  
spec:
  host: petclinic-app-pipelines.apps.enentodemocluster.janus.com
  path: /
  to:
    kind: Service
    name: petclinic-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
